### ISSUE TITLE
fix buckets and add settings 

### ISSUE THREAD

**Issue by Mathiaszero** [wsor4035/liquid_restriction#1]
According to default code in init, only those who have a server priv or are admins can place nodes above 30. However, I tested a regular "spill" player and that player can spill the bucket at any height, regardless whether the player has the elevated server privs.

**Comment by wsor4035** [comment]
"buckets don't work(place liquid) when used.
just use the node form of it. use default:water_source instead of bucket:bucket_water"

ive ment to get around to fixing the above(buckets are removed from inv currently) but haven't.
i would suspect your using a bucket from another another mod?

**Comment by Mathiaszero** [comment]
No I think I am using the default bucket. What I did change in your code was I commented out the removal of buckets from inventory and that is why the player has it. I think you clarified those.

**Comment by wsor4035** [comment]
you still currently shouldn't be able to place liquids at all with buckets unless you changed something else?

**Comment by wsor4035** [comment]
leaving this open as i do need to fix buckets

**Comment by Mathiaszero** [comment]
> 
> 
> you still currently shouldn't be able to place liquids at all with buckets unless you changed something else?

Yes, the part you just mentioned is working as how you intended. If I did not change anything in your code, I shouldn't have been able to.

Also, I am thankful that you are resuming work on this; I couldn't easily find any other _published_ mods out there and I think will benefit a lot of people.

**Comment by wsor4035** [comment]
well, not being able to place buckets is actually some broken i never fixed and just hid because i was working on other projects
since you seem interested, any other features you would like to see added?
also - i should have some time to work on this tommorrow

**Comment by wsor4035** [comment]
some things on my todo include making more things configurable via minetest.conf

**Comment by Mathiaszero** [comment]
Of course, you call the final shots, but I guess I can share some of my thoughts. I think the code `groups = {not_in_creative_inventory = 1}` should apply only to players who do not have the spill priv, since players who can spill stuff obviously should see those items in the guide.

As to spreading, it could be a configuration, but it could also be part of the priv system.

A further idea I have is several levels of privs:
"none": cannot see liquid/bucket inventory, cannot pick up water, lava, and other liquids
spill: can see liquid/bucket inventory and pickup/place/spill liquids, no spreading, height restriction
spill2: spill but with spreading, height restriction
spill3 or server: can use liquids freely, no height restriction

other configurations: allow user to specify range y min and y max for placing liquids, allow user to change how many nodes the liquid can spread, and I think you have a section in the code that puts all items in a table, which is easy to edit. But I think each table will be separated if the user specifies different depths, e.g. the user specifies that water be from 2 to -31000, and lava is from -15 to -31000 (in case there are multiple mapgens at various depths of the map)

I hope these ideas/thoughts help. If you do decide to consider these, it probably is quite a bit for now. I don't really have any other features to propose, but if there are it will probably be for a later version in the future.

**Comment by wsor4035** [comment]
@Mathiaszero can you update to commit `1e33fd0` (current as of writing) and test out buckets? currently working on settings atm

**Comment by Mathiaszero** [comment]
Yes, I should get it done soon.

Update: player with spill can now use bucket. The factor of the height restriction also works. When the player was above 30, the player could not spill.

I think even this commit itself is good for submitting publicly and a big improvement over the last one.

**Comment by wsor4035** [comment]
great! ill hopefully get to settings soon.
what do you mean by submitting publicly? its already in the master branch and on contentdb

**Comment by Mathiaszero** [comment]
Oh that's just me, I make minor changes to stuff and change the repository to private, then I make the repository public again when I think it looks good. It's an odd habit of mine.

**Comment by wsor4035** [comment]
heh, ok
not sure if i should do settings first or #2 - idk

**Comment by wsor4035** [comment]
@Mathiaszero could you check out commit `7cdca40` (current as of writing) please? adds 4 settings. are those configurations good? 

offtopic, just noticed that im using depends.txt, need to fix that

**Comment by wsor4035** [comment]
added mod.conf

**Comment by Mathiaszero** [comment]
Currently testing as of post; I will send a further update on the results.

Update: I applied the settings and tested, then changed all of them and see if they all still work. Everything appears to work correctly as intended. This is really good work you put in

**Comment by wsor4035** [comment]
any reason this cant be closed? ill get to #2 hopefully soon, feel free to file more issues here or dm me on discord otherwise

**Comment by Mathiaszero** [comment]
No, I don’t think there is anything else. Glad to have tested the mod, hope you continue to maintain/keep up to date/improve as needed, I think this should be an essential mod for MT

**Comment by wsor4035** [comment]
ok, sounds good
